package:
  name: fusemblr
  version: "1.0.0"  # Change this to your desired version

source:
  git_url: https://github.com/samtobam/fusemblr.git
  git_rev: main

build:
  number: 0 # Increment with each new build
  scripts:
    - python=3.8.*
    - bin/fusemblr
    - bash post-link.sh

requirements:
  run:
  - bioconda::ratatosk=0.9.0
  - bioconda::filtlong=0.2.1
  - bioconda::flye=2.9.5
  - bioconda::fastp=0.24.0
  - bioconda::nextpolish2=0.2.1
  - bioconda::seqkit=2.10.0
  - bioconda::samtools=1.21
  - bioconda::minimap2=2.28
  - bioconda::ragtag=2.1.0

test:
  commands:
    - "fusemblr.sh --help"

about:
  home: "https://github.com/samtobam/fusemblr"
  summary: "Assembly pipeline designed for Nanopore reads"
